FROM cschranz/gpu-jupyter

RUN pip install asap3 ase tqdm 
RUN pip install git+https://github.com/ulissigroup/sella.git
RUN pip install git+https://github.com/ulissigroup/amptorch.git
RUN pip install --no-deps git+https://github.com/MDIL-SNU/SIMPLE-NN.git
